#############################################################################
# Makefile for building: SynchronizationTool
# Generated by qmake (3.0) (Qt 5.2.1)
# Project:  SynchronizationTool.pro
# Template: subdirs
# Command: /usr/lib/x86_64-linux-gnu/qt5/bin/qmake -spec linux-g++-64 CONFIG+=debug -o Makefile SynchronizationTool.pro
#############################################################################

MAKEFILE      = Makefile

first: make_first
QMAKE         = /usr/lib/x86_64-linux-gnu/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
SUBTARGETS    =  \
		sub-ServerApplication \
		sub-ClientApplication


sub-ServerApplication-qmake_all:  FORCE
	@test -d ServerApplication/ || mkdir -p ServerApplication/
	cd ServerApplication/ && $(QMAKE) /home/mmichniewski/Pobrane/SynchronizationTool/SynchronizationTool/ServerApplication/ServerApplication.pro -spec linux-g++-64 CONFIG+=debug -o Makefile
	cd ServerApplication/ && $(MAKE) -f Makefile qmake_all
sub-ServerApplication: FORCE
	@test -d ServerApplication/ || mkdir -p ServerApplication/
	cd ServerApplication/ && ( test -e Makefile || $(QMAKE) /home/mmichniewski/Pobrane/SynchronizationTool/SynchronizationTool/ServerApplication/ServerApplication.pro -spec linux-g++-64 CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile
sub-ServerApplication-make_first: FORCE
	@test -d ServerApplication/ || mkdir -p ServerApplication/
	cd ServerApplication/ && ( test -e Makefile || $(QMAKE) /home/mmichniewski/Pobrane/SynchronizationTool/SynchronizationTool/ServerApplication/ServerApplication.pro -spec linux-g++-64 CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile 
sub-ServerApplication-all: FORCE
	@test -d ServerApplication/ || mkdir -p ServerApplication/
	cd ServerApplication/ && ( test -e Makefile || $(QMAKE) /home/mmichniewski/Pobrane/SynchronizationTool/SynchronizationTool/ServerApplication/ServerApplication.pro -spec linux-g++-64 CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile all
sub-ServerApplication-clean: FORCE
	@test -d ServerApplication/ || mkdir -p ServerApplication/
	cd ServerApplication/ && ( test -e Makefile || $(QMAKE) /home/mmichniewski/Pobrane/SynchronizationTool/SynchronizationTool/ServerApplication/ServerApplication.pro -spec linux-g++-64 CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile clean
sub-ServerApplication-distclean: FORCE
	@test -d ServerApplication/ || mkdir -p ServerApplication/
	cd ServerApplication/ && ( test -e Makefile || $(QMAKE) /home/mmichniewski/Pobrane/SynchronizationTool/SynchronizationTool/ServerApplication/ServerApplication.pro -spec linux-g++-64 CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile distclean
sub-ServerApplication-install_subtargets: FORCE
	@test -d ServerApplication/ || mkdir -p ServerApplication/
	cd ServerApplication/ && ( test -e Makefile || $(QMAKE) /home/mmichniewski/Pobrane/SynchronizationTool/SynchronizationTool/ServerApplication/ServerApplication.pro -spec linux-g++-64 CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile install
sub-ServerApplication-uninstall_subtargets: FORCE
	@test -d ServerApplication/ || mkdir -p ServerApplication/
	cd ServerApplication/ && ( test -e Makefile || $(QMAKE) /home/mmichniewski/Pobrane/SynchronizationTool/SynchronizationTool/ServerApplication/ServerApplication.pro -spec linux-g++-64 CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-ClientApplication-qmake_all:  FORCE
	@test -d ClientApplication/ || mkdir -p ClientApplication/
	cd ClientApplication/ && $(QMAKE) /home/mmichniewski/Pobrane/SynchronizationTool/SynchronizationTool/ClientApplication/ClientApplication.pro -spec linux-g++-64 CONFIG+=debug -o Makefile
	cd ClientApplication/ && $(MAKE) -f Makefile qmake_all
sub-ClientApplication: FORCE
	@test -d ClientApplication/ || mkdir -p ClientApplication/
	cd ClientApplication/ && ( test -e Makefile || $(QMAKE) /home/mmichniewski/Pobrane/SynchronizationTool/SynchronizationTool/ClientApplication/ClientApplication.pro -spec linux-g++-64 CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile
sub-ClientApplication-make_first: FORCE
	@test -d ClientApplication/ || mkdir -p ClientApplication/
	cd ClientApplication/ && ( test -e Makefile || $(QMAKE) /home/mmichniewski/Pobrane/SynchronizationTool/SynchronizationTool/ClientApplication/ClientApplication.pro -spec linux-g++-64 CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile 
sub-ClientApplication-all: FORCE
	@test -d ClientApplication/ || mkdir -p ClientApplication/
	cd ClientApplication/ && ( test -e Makefile || $(QMAKE) /home/mmichniewski/Pobrane/SynchronizationTool/SynchronizationTool/ClientApplication/ClientApplication.pro -spec linux-g++-64 CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile all
sub-ClientApplication-clean: FORCE
	@test -d ClientApplication/ || mkdir -p ClientApplication/
	cd ClientApplication/ && ( test -e Makefile || $(QMAKE) /home/mmichniewski/Pobrane/SynchronizationTool/SynchronizationTool/ClientApplication/ClientApplication.pro -spec linux-g++-64 CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile clean
sub-ClientApplication-distclean: FORCE
	@test -d ClientApplication/ || mkdir -p ClientApplication/
	cd ClientApplication/ && ( test -e Makefile || $(QMAKE) /home/mmichniewski/Pobrane/SynchronizationTool/SynchronizationTool/ClientApplication/ClientApplication.pro -spec linux-g++-64 CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile distclean
sub-ClientApplication-install_subtargets: FORCE
	@test -d ClientApplication/ || mkdir -p ClientApplication/
	cd ClientApplication/ && ( test -e Makefile || $(QMAKE) /home/mmichniewski/Pobrane/SynchronizationTool/SynchronizationTool/ClientApplication/ClientApplication.pro -spec linux-g++-64 CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile install
sub-ClientApplication-uninstall_subtargets: FORCE
	@test -d ClientApplication/ || mkdir -p ClientApplication/
	cd ClientApplication/ && ( test -e Makefile || $(QMAKE) /home/mmichniewski/Pobrane/SynchronizationTool/SynchronizationTool/ClientApplication/ClientApplication.pro -spec linux-g++-64 CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile uninstall

Makefile: SynchronizationTool.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/shell-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_location.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_positioning.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sensors.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_serialport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkit.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkit_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		SynchronizationTool.pro
	$(QMAKE) -spec linux-g++-64 CONFIG+=debug -o Makefile SynchronizationTool.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/shell-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_location.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_positioning.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sensors.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_serialport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkit.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkit_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
SynchronizationTool.pro:
qmake: FORCE
	@$(QMAKE) -spec linux-g++-64 CONFIG+=debug -o Makefile SynchronizationTool.pro

qmake_all: sub-ServerApplication-qmake_all sub-ClientApplication-qmake_all FORCE

make_first: sub-ServerApplication-make_first sub-ClientApplication-make_first FORCE
all: sub-ServerApplication-all sub-ClientApplication-all FORCE
clean: sub-ServerApplication-clean sub-ClientApplication-clean FORCE
distclean: sub-ServerApplication-distclean sub-ClientApplication-distclean FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-ServerApplication-install_subtargets sub-ClientApplication-install_subtargets FORCE
uninstall_subtargets: sub-ServerApplication-uninstall_subtargets sub-ClientApplication-uninstall_subtargets FORCE

sub-ServerApplication-check:
	@test -d ServerApplication/ || mkdir -p ServerApplication/
	cd ServerApplication/ && ( test -e Makefile || $(QMAKE) /home/mmichniewski/Pobrane/SynchronizationTool/SynchronizationTool/ServerApplication/ServerApplication.pro -spec linux-g++-64 CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile check
sub-ClientApplication-check:
	@test -d ClientApplication/ || mkdir -p ClientApplication/
	cd ClientApplication/ && ( test -e Makefile || $(QMAKE) /home/mmichniewski/Pobrane/SynchronizationTool/SynchronizationTool/ClientApplication/ClientApplication.pro -spec linux-g++-64 CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile check
check: sub-ServerApplication-check sub-ClientApplication-check
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

