#!/bin/bash
# Run Unit Tests

echo "--------------------------Run Unit Tests---------------------------"

cd /home/mmichniewski/Pulpit/build-SynchronizationTool-Desktop-Debug/ServerApplication/tests/auto/UnitTests/ChecksumTests
./ChecksumTests $1
cd ..

cd /home/mmichniewski/Pulpit/build-SynchronizationTool-Desktop-Debug/ServerApplication/tests/auto/UnitTests/CReceiverFactoryTests
./CReceiverFactoryTests $1
cd ..

cd /home/mmichniewski/Pulpit/build-SynchronizationTool-Desktop-Debug/ServerApplication/tests/auto/UnitTests/GetSettingsTests
./GetSettingsTests $1
cd ..

#RECEIVER TESTS:
cd /home/mmichniewski/Pulpit/build-SynchronizationTool-Desktop-Debug/ServerApplication/tests/auto/UnitTests/ReceiverTests/CalculateChecksumTests
./CalculateChecksumTests $1
cd ..

cd /home/mmichniewski/Pulpit/build-SynchronizationTool-Desktop-Debug/ServerApplication/tests/auto/UnitTests/ReceiverTests/ConnectionTests
./ConnectionTests $1
cd ..

cd /home/mmichniewski/Pulpit/build-SynchronizationTool-Desktop-Debug/ServerApplication/tests/auto/UnitTests/ReceiverTests/ConvertMessageArrayToIntTests
./ConvertMessageArrayToIntTests $1
cd ..

cd /home/mmichniewski/Pulpit/build-SynchronizationTool-Desktop-Debug/ServerApplication/tests/auto/UnitTests/ReceiverTests/DataMethodsTests
./DataMethodsTests $1
cd ..

cd /home/mmichniewski/Pulpit/build-SynchronizationTool-Desktop-Debug/ServerApplication/tests/auto/UnitTests/ReceiverTests/MessageFormatTests
./MessageFormatTests $1
cd ..

#SERVER TESTS:
cd /home/mmichniewski/Pulpit/build-SynchronizationTool-Desktop-Debug/ServerApplication/tests/auto/UnitTests/ServerTests/ListeningTests
./ListeningTests $1
cd ..

cd /home/mmichniewski/Pulpit/build-SynchronizationTool-Desktop-Debug/ServerApplication/tests/auto/UnitTests/ServerTests/ServerMethodsTests
./ServerMethodsTests $1
cd ..

cd /home/mmichniewski/Pulpit/build-SynchronizationTool-Desktop-Debug/ServerApplication/tests/auto/UnitTests/StorePhotoTests
./StorePhotoTests $1
cd ..

